cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "aws/tap"

brew "autoconf"
brew "awscli"
brew "exa"
brew "curl"
brew "git"
brew "gh"
brew "ghq"
brew "go"
brew "hadolint"
brew "jq"
brew "mas"
brew "openjdk@17"
brew "peco"
brew "plantuml"
brew "pylint"
brew "python@3.11"
brew "shellcheck"
brew "the_silver_searcher"
brew "telnet"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"

# cask "dbeaver-community"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "intellij-idea"
cask "postman"
# cask "rancher"
# cask "raycast"
cask "slack"
cask "visual-studio-code"
cask "zoom"
