name: lint

on:
  push:
    paths:
      - '**.sh'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v2
        env:
          shellcheck_flags: --exclude=SC1090